# Generated by Django 6.0.5 on 2026-05-28 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='photo',
        ),
        migrations.AlterField(
            model_name='clothes',
            name='name',
            field=models.CharField(max_length=100, verbose_name='введите название одежды'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.CharField(max_length=100, verbose_name='стоимость одежды'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='text',
            field=models.TextField(verbose_name='описание. например размер, цвет и прочее'),
        ),
        migrations.CreateModel(
            name='ClothesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clothes/')),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.clothes')),
            ],
        ),
    ]
