# Generated by Django 6.0.5 on 2026-06-01 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_clothes_image_delete_clothesimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Официант',
                'verbose_name_plural': 'Официанты',
            },
        ),
    ]
